// Nationwide Indian Ministries & Inter-Departmental Cascading Dependencies
// Covers 30 Government of India Ministries/Departments and 100+ Sub-sectors.
// Models cross-sector lifelines, multi-hazard domino effects, time-to-cascade buffers,
// and actionable citizen/administrative advisories.

export const DEPARTMENTS = [
  {
    id: "animal_care",
    name: "Animal Husbandry & Dairying",
    ministry: "Ministry of Fisheries, Animal Husbandry & Dairying",
    category: "Ecological & Agri",
    icon: "fa-paw",
    color: "amber",
    description: "Veterinary emergency care, milk cold chains, livestock shelters, fodder supplies, and zoonotic disease control.",
  },
  {
    id: "agriculture_plants",
    name: "Agriculture & Crop Protection",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    category: "Ecological & Agri",
    icon: "fa-seedling",
    color: "emerald",
    description: "Seed reserves, grain silos, fertilizer distribution, canal irrigation networks, and crop loss mitigation.",
  },
  {
    id: "road_transport",
    name: "Road Transport & Highways",
    ministry: "Ministry of Road Transport & Highways",
    category: "Lifeline & Logistics",
    icon: "fa-road",
    color: "orange",
    description: "National highways, arterial bridges, ghat-pass tunnels, and heavy freight logistics corridors.",
  },
  {
    id: "railways",
    name: "Indian Railways Network",
    ministry: "Ministry of Railways",
    category: "Lifeline & Logistics",
    icon: "fa-train",
    color: "blue",
    description: "High-density passenger lines, dedicated freight corridors, electric traction grids, and automated interlocking signals.",
  },
  {
    id: "civil_aviation",
    name: "Civil Aviation & Airspace",
    ministry: "Ministry of Civil Aviation",
    category: "Lifeline & Logistics",
    icon: "fa-plane-departure",
    color: "sky",
    description: "Air traffic control (ATC), regional runways, emergency medevac helipads, and aviation turbine fuel storage.",
  },
  {
    id: "ports_shipping",
    name: "Ports, Shipping & Waterways",
    ministry: "Ministry of Ports, Shipping & Waterways",
    category: "Lifeline & Logistics",
    icon: "fa-anchor",
    color: "teal",
    description: "Major container docks, coastal crude oil berths, inland waterway barges, and cyclone harbor shelters.",
  },
  {
    id: "power_energy",
    name: "Power & Renewable Grid",
    ministry: "Ministry of Power & MNRE",
    category: "Critical Lifeline",
    icon: "fa-bolt",
    color: "yellow",
    description: "Ultra-high-voltage substations, regional load dispatch centers (RLDC), hydro/thermal generation, and distribution feeders.",
  },
  {
    id: "petroleum_gas",
    name: "Petroleum & Natural Gas",
    ministry: "Ministry of Petroleum & Natural Gas",
    category: "Critical Lifeline",
    icon: "fa-gas-pump",
    color: "red",
    description: "City piped gas (PNG) networks, strategic fuel refineries, LPG bottling depots, and emergency diesel reserves.",
  },
  {
    id: "water_resources",
    name: "Water Resources (Jal Shakti)",
    ministry: "Ministry of Jal Shakti",
    category: "Critical Lifeline",
    icon: "fa-droplet",
    color: "cyan",
    description: "Major storage dams, reservoir sluice gates, municipal drinking water treatment, and flood protection bunds.",
  },
  {
    id: "markets_food",
    name: "Wholesale Markets & Food Supply",
    ministry: "Ministry of Consumer Affairs, Food & Public Distribution",
    category: "Economy & Supplies",
    icon: "fa-cart-shopping",
    color: "lime",
    description: "APMC wholesale mandis, public distribution (PDS) ration hubs, FCI buffer silos, and urban grocery chains.",
  },
  {
    id: "healthcare",
    name: "Healthcare & Critical Medicine",
    ministry: "Ministry of Health & Family Welfare",
    category: "Critical Lifeline",
    icon: "fa-hospital",
    color: "rose",
    description: "Level-1 trauma centers, ICU wards, medical liquid oxygen storage, blood banks, and ambulance dispatch.",
  },
  {
    id: "telecom",
    name: "Telecommunications & Cell Towers",
    ministry: "Ministry of Communications (DoT)",
    category: "Critical Lifeline",
    icon: "fa-tower-cell",
    color: "violet",
    description: "Cellular base stations, underground optical fiber backhauls, satellite uplinks, and National 112 emergency routing.",
  },
  {
    id: "tourism_hospitality",
    name: "Tourism & Pilgrim Corridors",
    ministry: "Ministry of Tourism",
    category: "Economy & Social",
    icon: "fa-mountain-sun",
    color: "fuchsia",
    description: "High-altitude pilgrimage shrines, mountain resorts, passenger cable cars/ropeways, and heritage sanctuaries.",
  },
  {
    id: "environment_forest",
    name: "Environment, Forests & Climate",
    ministry: "Ministry of Environment, Forest & Climate Change",
    category: "Ecological & Agri",
    icon: "fa-tree",
    color: "emerald",
    description: "Wildlife sanctuaries, forest fire watchtowers, coastal mangrove surge barriers, and catchment wetlands.",
  },
  {
    id: "banking_finance",
    name: "Banking, UPI & Digital Finance",
    ministry: "Ministry of Finance & RBI/NPCI",
    category: "Economy & Supplies",
    icon: "fa-building-columns",
    color: "indigo",
    description: "ATM networks, NPCI/UPI immediate payment switch, commercial currency chests, and settlement gateways.",
  },
  {
    id: "urban_infrastructure",
    name: "Urban Municipal Infrastructure",
    ministry: "Ministry of Housing & Urban Affairs",
    category: "Urban & Municipal",
    icon: "fa-city",
    color: "slate",
    description: "Stormwater drainage pumping, high-rise residential elevators, municipal fire & rescue brigades, and sewage plants.",
  },
  {
    id: "heavy_industries",
    name: "Heavy Industries & Manufacturing",
    ministry: "Ministry of Heavy Industries",
    category: "Industry & Safety",
    icon: "fa-industry",
    color: "stone",
    description: "Chemical manufacturing, HAZMAT containment, steel blast furnaces, and industrial gas production.",
  },
  {
    id: "chemicals_petrochem",
    name: "Chemicals & Fertilizers",
    ministry: "Ministry of Chemicals & Fertilizers",
    category: "Industry & Safety",
    icon: "fa-flask-vial",
    color: "purple",
    description: "Chlorine water-purification chemical stocks, agricultural ammonia, industrial solvents, and pesticide reserves.",
  },
  {
    id: "mines_coal",
    name: "Coal & Mineral Mining",
    ministry: "Ministry of Coal & Mines",
    category: "Industry & Safety",
    icon: "fa-cubes-stacked",
    color: "zinc",
    description: "Open-cast coal pitheads, underground pit ventilation, slurry dams, and thermal power plant fuel rail-rakes.",
  },
  {
    id: "education",
    name: "Education & Public Shelters",
    ministry: "Ministry of Education",
    category: "Economy & Social",
    icon: "fa-graduation-cap",
    color: "amber",
    description: "Government school buildings (primary evacuation shelters), university hostels, and centralized mid-day meal kitchens.",
  },
  {
    id: "home_affairs",
    name: "Home Affairs & Disaster Response",
    ministry: "Ministry of Home Affairs (MHA)",
    category: "Governance & Security",
    icon: "fa-shield-halved",
    color: "red",
    description: "National Disaster Response Force (NDRF), State Disaster Response Forces (SDRF), civil defence, and district police.",
  },
  {
    id: "defense_border",
    name: "Defence & Border Roads (BRO)",
    ministry: "Ministry of Defence & BRO",
    category: "Governance & Security",
    icon: "fa-jet-fighter",
    color: "neutral",
    description: "Border strategic highways, military airbases, heavy bridging logistics, and humanitarian search-and-rescue flights.",
  },
  {
    id: "coastal_fisheries",
    name: "Coastal Fisheries & Marine Safety",
    ministry: "Department of Fisheries",
    category: "Ecological & Agri",
    icon: "fa-fish",
    color: "blue",
    description: "Deep-sea mechanized fishing fleets, harbor ice plants, marine communication channels, and coastal warning buoys.",
  },
  {
    id: "it_electronics",
    name: "Information Technology & Data Centers",
    ministry: "Ministry of Electronics & IT (MeitY)",
    category: "Critical Lifeline",
    icon: "fa-server",
    color: "cyan",
    description: "State data centers, national cloud infrastructure, citizen verification APIs (Aadhaar/DigiLocker), and cyber forensics.",
  },
  {
    id: "commerce_logistics",
    name: "Commerce & Freight Supply Chains",
    ministry: "Ministry of Commerce & Industry",
    category: "Economy & Supplies",
    icon: "fa-truck-moving",
    color: "orange",
    description: "Inland container depots (ICD), inter-state multi-modal logistics parks (MMLP), and cold-chain truck fleets.",
  },
  {
    id: "rural_development",
    name: "Rural Development & Panchayats",
    ministry: "Ministry of Rural Development & Panchayati Raj",
    category: "Governance & Security",
    icon: "fa-handshake-angle",
    color: "emerald",
    description: "Gram Panchayat village communication centers, PMGSY all-weather rural link roads, and community borewells.",
  },
  {
    id: "textiles",
    name: "Textiles & Emergency Fabrics",
    ministry: "Ministry of Textiles",
    category: "Economy & Supplies",
    icon: "fa-shirt",
    color: "pink",
    description: "Cotton warehousing, synthetic shelter tarpaulins, emergency blanket manufacturing, and protective relief gear.",
  },
  {
    id: "labour_employment",
    name: "Labour & Migrant Welfare",
    ministry: "Ministry of Labour & Employment",
    category: "Economy & Social",
    icon: "fa-helmet-safety",
    color: "amber",
    description: "Migrant worker transit hubs, industrial labor colonies, informal worker safety registries, and emergency compensation.",
  },
  {
    id: "space_science",
    name: "Space Telemetry & Geospatial (ISRO)",
    ministry: "Department of Space (ISRO) & DST",
    category: "Critical Lifeline",
    icon: "fa-satellite",
    color: "sky",
    description: "INSAT meteorological satellites, NavIC geospatial positioning, disaster ground tracking telemetry, and seismic arrays.",
  },
  {
    id: "women_child",
    name: "Women & Child Nutrition",
    ministry: "Ministry of Women & Child Development",
    category: "Economy & Social",
    icon: "fa-baby",
    color: "rose",
    description: "Anganwadi nutrition centers, infant milk and baby food stockpiles, maternity health posts, and orphan crisis protection.",
  },
];

export const SUBSECTORS = [
  // 1. ANIMAL CARE
  {
    id: "vet_cold_chain",
    name: "Veterinary Vaccine & Serum Cold Chain",
    deptId: "animal_care",
    code: "AC-1",
    reserveHours: 4,
    criticality: 0.82,
    description: "Refrigerated storehouses for livestock vaccines, anti-venom, and artificial insemination supplies.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 120, reason: "Loss of grid electricity depletes inverter backup, risking spoilage of vital livestock medicines." },
      { targetId: "highway_corridors", weight: 0.6, lagMinutes: 240, reason: "Highway disruption blocks liquid nitrogen refilling tankers." },
    ],
    citizenAdvisory: "Keep domestic livestock in shaded shelters; immediately report animal distress to Veterinary Helpline 1962.",
    authorityAction: "Deploy mobile generator units and solar-backed portable refrigeration boxes to regional veterinary hubs.",
  },
  {
    id: "dairy_milk_collection",
    name: "Dairy Chilling & Milk Collection Hubs",
    deptId: "animal_care",
    code: "AC-2",
    reserveHours: 5,
    criticality: 0.88,
    description: "Village-level bulk milk coolers and automated collection points serving dairy farming cooperatives.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.85, lagMinutes: 150, reason: "Chilling plants shut down; raw milk turns sour within 4 to 5 hours at ambient tropical temperatures." },
      { targetId: "rural_roads", weight: 0.75, lagMinutes: 180, reason: "Milk collection tankers cannot reach rural procurement centers." },
    ],
    citizenAdvisory: "Boil fresh dairy milk immediately upon purchase; prioritize baby milk formulas if regional supply slows.",
    authorityAction: "Issue emergency transit passes for dairy transport and divert backup diesel generators to major district chilling plants.",
  },
  {
    id: "livestock_shelters",
    name: "Livestock Evacuation & Fodder Silos",
    deptId: "animal_care",
    code: "AC-3",
    reserveHours: 24,
    criticality: 0.79,
    description: "Raised mounds and high-ground shelters for cattle, goats, and poultry during seasonal floods.",
    upstreamDependencies: [
      { targetId: "drinking_water_plants", weight: 0.8, lagMinutes: 360, reason: "Cattle herds face acute dehydration if municipal water lines and livestock troughs dry up." },
      { targetId: "highway_corridors", weight: 0.65, lagMinutes: 480, reason: "Dry fodder and feed trucks stuck in highway bottlenecks." },
    ],
    citizenAdvisory: "Untether cattle and farm animals from low-lying sheds so they can swim to higher ground if floodwaters rise.",
    authorityAction: "Mobilize NDRF animal rescue boats and release emergency dry-fodder stocks from district contingency reserves.",
  },

  // 2. AGRICULTURE & PLANTS
  {
    id: "grain_silos_fci",
    name: "FCI Grain Silos & Buffer Stocks",
    deptId: "agriculture_plants",
    code: "AG-1",
    reserveHours: 48,
    criticality: 0.91,
    description: "Strategic food-grain storage domes and mechanized wheat/rice grain elevators.",
    upstreamDependencies: [
      { targetId: "rail_freight_corridors", weight: 0.85, lagMinutes: 720, reason: "Inability to load bulk grain rakes creates nationwide supply shortages in disaster-hit zones." },
      { targetId: "power_substations", weight: 0.7, lagMinutes: 300, reason: "Loss of aeration fans allows damp grain to rot from mold and moisture condensation." },
    ],
    citizenAdvisory: "Maintain a 14-day domestic dry-ration buffer (rice, lentils, flour); do not panic-hoard staple commodities.",
    authorityAction: "Requisition military-grade tarpaulins and activate diesel blowers to prevent waterlogging at grain terminals.",
  },
  {
    id: "canal_irrigation",
    name: "Barrage Sluices & Irrigation Canals",
    deptId: "agriculture_plants",
    code: "AG-2",
    reserveHours: 8,
    criticality: 0.86,
    description: "Major water distribution canals regulating irrigation to tens of thousands of hectares of farmland.",
    upstreamDependencies: [
      { targetId: "dam_reservoirs", weight: 0.95, lagMinutes: 60, reason: "Uncontrolled reservoir releases rupture canal earthen bunds, submerging standing crops." },
      { targetId: "telecom_towers", weight: 0.6, lagMinutes: 120, reason: "Loss of remote SCADA telemetry blinds irrigation engineers to downstream surge levels." },
    ],
    citizenAdvisory: "Stay clear of canal banks and low-lying field dykes; move farm machinery to elevated road embankments.",
    authorityAction: "Deploy manual sluice-gate operating teams equipped with satellite phones to regulate agricultural canal discharge.",
  },
  {
    id: "fertilizer_distribution",
    name: "Chemical Fertilizer Storage & Seeds",
    deptId: "agriculture_plants",
    code: "AG-3",
    reserveHours: 72,
    criticality: 0.72,
    description: "Urea, DAP, and certified seed warehouses critical for immediate post-disaster replanting.",
    upstreamDependencies: [
      { targetId: "chemical_plants", weight: 0.8, lagMinutes: 1440, reason: "Industrial ammonia shortages halt domestic urea formulation." },
      { targetId: "highway_corridors", weight: 0.7, lagMinutes: 480, reason: "Fertilizer trucks unable to reach cooperative marketing societies." },
    ],
    citizenAdvisory: "Ensure stored seeds are elevated on wooden pallets away from ground dampness and flood runoff.",
    authorityAction: "Pre-position waterproof seed vaults in high-altitude community centers before monsoon cyclone season.",
  },

  // 3. ROAD TRANSPORT & HIGHWAYS
  {
    id: "highway_corridors",
    name: "National Highway Arterial Corridors",
    deptId: "road_transport",
    code: "RT-1",
    reserveHours: 2,
    criticality: 0.96,
    description: "Four-to-six-lane national highways carrying over 70% of inter-state freight and relief convoys.",
    upstreamDependencies: [
      { targetId: "bridges_culverts", weight: 0.95, lagMinutes: 30, reason: "Collapse or structural scour of a single arterial bridge severs the entire highway corridor." },
      { targetId: "urban_drainage", weight: 0.7, lagMinutes: 60, reason: "Urban underpasses and highway low-points flood under 2 meters of stormwater." },
    ],
    citizenAdvisory: "Avoid non-essential highway travel; follow official traffic police diversions and GPS navigation alerts.",
    authorityAction: "Deploy quick-deploy Bailey bridge units (BRO/Army) and enforce an exclusive Green Corridor for relief ambulances and food trucks.",
  },
  {
    id: "bridges_culverts",
    name: "Arterial River Bridges & Flyovers",
    deptId: "road_transport",
    code: "RT-2",
    reserveHours: 1,
    criticality: 0.98,
    description: "Critical river spans, flyovers, and elevated causeways connecting isolated administrative districts.",
    upstreamDependencies: [
      { targetId: "dam_reservoirs", weight: 0.9, lagMinutes: 45, reason: "Flash-flood hydraulic forces erode foundation piers and wash out bridge approaches." },
    ],
    citizenAdvisory: "Never attempt to drive or walk across a submerged bridge or causeway; swift water can sweep away vehicles.",
    authorityAction: "Order immediate visual and sonar pier-scour inspections; shut traffic barricades when water touches girder bearings.",
  },
  {
    id: "ghat_mountain_tunnels",
    name: "Mountain Ghat Passes & Tunnels",
    deptId: "road_transport",
    code: "RT-3",
    reserveHours: 6,
    criticality: 0.89,
    description: "Engineered passes in Western Ghats, Himachal, and Uttarakhand vulnerable to landslides and rockfalls.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.75, lagMinutes: 30, reason: "Tunnel ventilation fans and lighting systems fail, causing toxic carbon monoxide accumulation inside tunnels." },
    ],
    citizenAdvisory: "Do not halt vehicles beneath steep, unreinforced rock cuttings during intense cloudbursts or continuous rain.",
    authorityAction: "Station heavy excavators, bulldozers, and rock-clearing explosive teams at both ends of critical mountain tunnels.",
  },

  // 4. RAILWAYS
  {
    id: "rail_passenger_lines",
    name: "High-Density Rail Passenger Network",
    deptId: "railways",
    code: "RW-1",
    reserveHours: 3,
    criticality: 0.93,
    description: "Electrified trunk routes carrying millions of passengers daily between metropolitan centers.",
    upstreamDependencies: [
      { targetId: "traction_power_grid", weight: 0.95, lagMinutes: 15, reason: "Overhead 25kV traction grid failure strands express trains in remote territory without AC or water." },
      { targetId: "rail_signaling", weight: 0.9, lagMinutes: 20, reason: "Signaling malfunction automatically triggers red safety interlocks, halting all train movements." },
    ],
    citizenAdvisory: "Check IRCTC live train running status before leaving for stations; stay inside coaches if a train is halted in open terrain.",
    authorityAction: "Dispatch diesel locomotive recovery engines to tow stranded electric passenger trains to the nearest junction station.",
  },
  {
    id: "traction_power_grid",
    name: "Rail Traction Substations (25kV OHE)",
    deptId: "railways",
    code: "RW-2",
    reserveHours: 1,
    criticality: 0.94,
    description: "Specialized traction substations converting high-voltage state grid power into 25kV rail overhead wires.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.98, lagMinutes: 10, reason: "Regional state grid collapse de-energizes the traction feeders instantly." },
    ],
    citizenAdvisory: "Never touch fallen rail cables; 25,000-volt lines can arc and cause lethal electrocution.",
    authorityAction: "Isolate damaged feeder sections and back-feed critical trunk routes from adjacent unaffected grid zones.",
  },
  {
    id: "rail_signaling",
    name: "Automated Rail Signalling & Interlocking",
    deptId: "railways",
    code: "RW-3",
    reserveHours: 4,
    criticality: 0.96,
    description: "Electronic interlocking, track circuits, and axle counters preventing train collisions.",
    upstreamDependencies: [
      { targetId: "telecom_towers", weight: 0.7, lagMinutes: 45, reason: "Loss of fiber telemetry disconnects divisional centralized traffic control (CTC) centers." },
      { targetId: "urban_drainage", weight: 0.8, lagMinutes: 30, reason: "Waterlogged tracks short-circuit signaling track relays, triggering fail-safe red halts." },
    ],
    citizenAdvisory: "Expect train schedule cancellations during heavy monsoon track waterlogging.",
    authorityAction: "Deploy manual pilot crews and flag-signaling teams to guide emergency relief rakes through junction yards.",
  },
  {
    id: "rail_freight_corridors",
    name: "Dedicated Freight Corridors (DFCs)",
    deptId: "railways",
    code: "RW-4",
    reserveHours: 8,
    criticality: 0.9,
    description: "Bulk freight rakes transporting thermal coal, grain, cement, and petroleum tankers across states.",
    upstreamDependencies: [
      { targetId: "traction_power_grid", weight: 0.9, lagMinutes: 60, reason: "Freight rakes halted, starving power plants of coal and cities of food within 48 hours." },
    ],
    citizenAdvisory: "Industrial manufacturers should check freight consignment tracking for vital raw material supplies.",
    authorityAction: "Prioritize green paths for emergency oxygen, petroleum, and food grain freight rakes over all other traffic.",
  },

  // 5. CIVIL AVIATION
  {
    id: "air_traffic_control",
    name: "Air Traffic Control (ATC) & Radars",
    deptId: "civil_aviation",
    code: "CA-1",
    reserveHours: 2,
    criticality: 0.97,
    description: "Primary and secondary surveillance radars, ILS approach systems, and VHF voice air communications.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 20, reason: "ATC relies on dual diesel generators; fuel or battery switchgear failure shuts down airspace control." },
      { targetId: "telecom_towers", weight: 0.85, lagMinutes: 15, reason: "Severed telecom backhauls disrupt flight coordination with international air traffic corridors." },
    ],
    citizenAdvisory: "Expect flight diversions and delays; do not leave for airport without airline confirmation.",
    authorityAction: "Switch to secondary remote VHF backup towers and clear holding patterns by diverting inbound flights to inland hubs.",
  },
  {
    id: "airport_runways",
    name: "Airport Runways & Medevac Helipads",
    deptId: "civil_aviation",
    code: "CA-2",
    reserveHours: 6,
    criticality: 0.88,
    description: "Surfaced runways, taxiways, and specialized helipads for emergency NDRF and IAF relief aircraft.",
    upstreamDependencies: [
      { targetId: "urban_drainage", weight: 0.85, lagMinutes: 90, reason: "Runway water accumulation over 3mm induces aircraft hydroplaning, closing the airport." },
      { targetId: "fuel_refineries", weight: 0.8, lagMinutes: 240, reason: "Shortage of Aviation Turbine Fuel (ATF) limits military transport rescue sorties." },
    ],
    citizenAdvisory: "Check DGCA and airport authority advisories for flight cancellation refund procedures.",
    authorityAction: "Deploy high-capacity runway de-watering pumps and clear dedicated helipads for Army air-drop helicopters.",
  },

  // 6. PORTS, SHIPPING & WATERWAYS
  {
    id: "port_container_docks",
    name: "Major Port Container Docks & Cranes",
    deptId: "ports_shipping",
    code: "PS-1",
    reserveHours: 12,
    criticality: 0.84,
    description: "Quayside gantry cranes, container freight stations, and bulk cargo berths handling import/export lifelines.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 60, reason: "Ship-to-shore gantry cranes require massive electric grid power; cargo handling freezes entirely." },
      { targetId: "highway_corridors", weight: 0.85, lagMinutes: 180, reason: "Container trucks back up for miles outside port gates, creating severe supply chain choke-points." },
    ],
    citizenAdvisory: "Importers and retail businesses should anticipate 5 to 7-day delays in imported electronic and medical equipment.",
    authorityAction: "Prioritize unloading of emergency medical shipments, specialized water purifiers, and disaster gear.",
  },
  {
    id: "coastal_oil_terminals",
    name: "Coastal Crude Oil & LNG Marine Berths",
    deptId: "ports_shipping",
    code: "PS-2",
    reserveHours: 24,
    criticality: 0.92,
    description: "Deep-water mooring buoys and pipeline manifolds receiving crude oil and liquefied natural gas (LNG) tankers.",
    upstreamDependencies: [
      { targetId: "weather_satellites", weight: 0.7, lagMinutes: 120, reason: "High swell warnings and tidal surges force oil tankers to decouple hoses and steam out to open sea." },
    ],
    citizenAdvisory: "Expect potential temporary fluctuations in commercial LPG and industrial gas supplies.",
    authorityAction: "Activate automated quick-release dry-break couplings to prevent maritime crude spills in choppy cyclone waters.",
  },

  // 7. POWER & RENEWABLE GRID
  {
    id: "power_substations",
    name: "High-Voltage Grid Substations (400kV/220kV)",
    deptId: "power_energy",
    code: "PE-1",
    reserveHours: 1,
    criticality: 0.99,
    description: "The primary backbone of the regional grid, stepping down bulk electricity for district distribution.",
    upstreamDependencies: [
      { targetId: "thermal_hydro_plants", weight: 0.95, lagMinutes: 10, reason: "Tripping of generation plants causes rapid grid frequency deviation, triggering automatic blackout tripwires." },
      { targetId: "urban_drainage", weight: 0.75, lagMinutes: 45, reason: "Flooding of substation transformer switchyards forces safety shutdowns to prevent catastrophic explosions." },
    ],
    citizenAdvisory: "Charge all emergency lights, phones, and power banks; unplug sensitive appliances to avoid high-voltage surge damage.",
    authorityAction: "Isolate flooded feeder bays; energize islanded micro-grids for critical healthcare corridors and water pumps.",
  },
  {
    id: "thermal_hydro_plants",
    name: "Thermal & Hydroelectric Generating Plants",
    deptId: "power_energy",
    code: "PE-2",
    reserveHours: 18,
    criticality: 0.95,
    description: "Major gigawatt generation facilities providing baseload electricity across state boundaries.",
    upstreamDependencies: [
      { targetId: "coal_mines_rakes", weight: 0.9, lagMinutes: 1440, reason: "Thermal stations run out of coal if railway mineral corridors are severed, forcing generation curtailment." },
      { targetId: "dam_reservoirs", weight: 0.85, lagMinutes: 60, reason: "Hydro turbines trip if intake trash racks choke with silt, logs, and landslide debris." },
    ],
    citizenAdvisory: "Practice energy conservation; turn off high-power air conditioners and heavy domestic loads.",
    authorityAction: "Divert emergency coal freight rakes to critical pithead plants and flush silt gates at hydro-power dams.",
  },
  {
    id: "city_distribution_feeders",
    name: "City Distribution Feeders & Transformers",
    deptId: "power_energy",
    code: "PE-3",
    reserveHours: 2,
    criticality: 0.91,
    description: "11kV residential and commercial distribution cables and local pole-mounted step-down transformers.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.98, lagMinutes: 15, reason: "Direct dependence on regional transmission substations." },
    ],
    citizenAdvisory: "Never approach fallen electric poles or water-covered transformer enclosures; report sparks to Helpline 1912.",
    authorityAction: "Deploy rapid electrical line-repair squads equipped with chainsaw cranes to clear fallen trees from overhead wires.",
  },

  // 8. PETROLEUM & NATURAL GAS
  {
    id: "fuel_refineries",
    name: "Petroleum Refineries & Depot Terminals",
    deptId: "petroleum_gas",
    code: "PG-1",
    reserveHours: 36,
    criticality: 0.93,
    description: "Large crude distillation units and strategic bulk storage tanks for diesel, petrol, and kerosene.",
    upstreamDependencies: [
      { targetId: "coastal_oil_terminals", weight: 0.9, lagMinutes: 360, reason: "Inability to offload marine tankers halts crude distillation units." },
      { targetId: "power_substations", weight: 0.8, lagMinutes: 60, reason: "Refinery internal operations trip on power dips, venting excess hydrocarbons to flares." },
    ],
    citizenAdvisory: "Ration domestic fuel usage; avoid panic-buying petrol at pump stations.",
    authorityAction: "Ring-fence 30% of depot diesel inventory exclusively for disaster relief machinery, ambulances, and emergency generators.",
  },
  {
    id: "city_gas_png",
    name: "Piped Natural Gas (PNG) City Grids",
    deptId: "petroleum_gas",
    code: "PG-2",
    reserveHours: 2,
    criticality: 0.89,
    description: "Pressurized underground pipeline network delivering natural gas directly to residential kitchens and industrial units.",
    upstreamDependencies: [
      { targetId: "telecom_towers", weight: 0.6, lagMinutes: 30, reason: "SCADA valve telematics lose connectivity during seismic shocks, prompting manual inspection shut-offs." },
    ],
    citizenAdvisory: "If you smell rotten-egg gas odor, do not turn on any electrical switches or strike matches; evacuate outdoors immediately.",
    authorityAction: "Trigger automated sectional shut-off tripwire valves within 15 seconds of earthquake P-wave alert to prevent urban conflagrations.",
  },
  {
    id: "lpg_bottling_plants",
    name: "LPG Cylinder Bottling Depots",
    deptId: "petroleum_gas",
    code: "PG-3",
    reserveHours: 48,
    criticality: 0.85,
    description: "Bottling plants filling pressurized cooking gas cylinders for millions of Indian households.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.85, lagMinutes: 480, reason: "Bulk pressurized bullet tankers unable to negotiate flooded or damaged highway corridors." },
    ],
    citizenAdvisory: "Use cooking gas sparingly; prepare ready-to-eat dry meals if refilling cycles are disrupted.",
    authorityAction: "Prioritize LPG delivery to community relief kitchens, hospitals, and disaster evacuation shelters.",
  },

  // 9. WATER RESOURCES (JAL SHAKTI)
  {
    id: "dam_reservoirs",
    name: "Major Dam Reservoirs & Sluice Gates",
    deptId: "water_resources",
    code: "JS-1",
    reserveHours: 6,
    criticality: 0.98,
    description: "Storage reservoirs regulating millions of cubic meters of water, flood moderation, and river discharges.",
    upstreamDependencies: [
      { targetId: "weather_satellites", weight: 0.8, lagMinutes: 120, reason: "Lack of cloudburst forecasts delays phased emergency water discharge, leading to sudden downstream deluge." },
      { targetId: "power_substations", weight: 0.7, lagMinutes: 30, reason: "Electrically operated radial spillway gates require immediate diesel generator switch-over." },
    ],
    citizenAdvisory: "Residents in downstream river floodplains must evacuate to high ground the moment dam sirens sound.",
    authorityAction: "Institute continuous rule-curve releases to absorb upstream mountain cloudbursts; coordinate inter-state dam notifications.",
  },
  {
    id: "drinking_water_plants",
    name: "Potable Water Treatment & Pumping",
    deptId: "water_resources",
    code: "JS-2",
    reserveHours: 8,
    criticality: 0.97,
    description: "Municipal treatment facilities filtering raw river water, chlorinating, and pumping drinking water to city reservoirs.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 60, reason: "Massive high-head intake pumps halt without electricity, drying city taps within 6 to 8 hours." },
      { targetId: "chlorine_chemical_stocks", weight: 0.85, lagMinutes: 360, reason: "Depleted chlorine gas supplies render treated water biologically unsafe, risking cholera outbreaks." },
    ],
    citizenAdvisory: "BOIL ALL DRINKING WATER for at least 3 minutes; use water-purification chlorine tablets distributed by relief teams.",
    authorityAction: "Deploy high-power mobile diesel generator sets directly to river intake pumphouses and dispatch municipal water tankers.",
  },
  {
    id: "river_embankments",
    name: "River Embankments & Flood Bunds",
    deptId: "water_resources",
    code: "JS-3",
    reserveHours: 3,
    criticality: 0.92,
    description: "Earthen dykes and stone-armored spurs protecting thousands of riverside villages and towns from inundation.",
    upstreamDependencies: [
      { targetId: "dam_reservoirs", weight: 0.9, lagMinutes: 90, reason: "Peak discharges exceeding designed return periods breach or overtop earthen embankments." },
    ],
    citizenAdvisory: "Do not build temporary huts on the river side of protective bunds; report any bund seepage or piping to authorities.",
    authorityAction: "Pre-position millions of sandbags, wire geocages, and heavy stone boulders with army engineering task forces.",
  },

  // 10. WHOLESALE MARKETS & FOOD SUPPLY
  {
    id: "apmc_wholesale_mandis",
    name: "APMC Wholesale Mandis & Grain Markets",
    deptId: "markets_food",
    code: "MF-1",
    reserveHours: 24,
    criticality: 0.87,
    description: "Centralized agricultural produce market committees where wholesale vegetables, grains, and fruits trade.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.9, lagMinutes: 360, reason: "Vegetable and onion trucks stranded on severed highway passes; wholesale prices spike 300% within 2 days." },
      { targetId: "banking_upi_atm", weight: 0.65, lagMinutes: 120, reason: "Cash and digital payment blackouts paralyze commission agents and daily-wage headload laborers." },
    ],
    citizenAdvisory: "Expect fresh vegetable price volatility; purchase essential dried legumes and potatoes from government cooperative counters.",
    authorityAction: "Cap wholesale prices on essential commodities under the Essential Commodities Act and arrange emergency grain convoys.",
  },
  {
    id: "pds_ration_shops",
    name: "Public Distribution (PDS) Fair Price Shops",
    deptId: "markets_food",
    code: "MF-2",
    reserveHours: 48,
    criticality: 0.91,
    description: "Over 500,000 neighborhood fair-price shops providing subsidized grain and oil to low-income families.",
    upstreamDependencies: [
      { targetId: "grain_silos_fci", weight: 0.85, lagMinutes: 720, reason: "Interruption of state civil supply trucks depletes local ration shop quotas." },
      { targetId: "telecom_towers", weight: 0.7, lagMinutes: 60, reason: "Electronic Point of Sale (ePoS) biometric Aadhaar verification fails if internet backhaul drops." },
    ],
    citizenAdvisory: "Ration card holders can collect emergency food quotas; offline manual register mode is activated if biometric machines fail.",
    authorityAction: "Authorise emergency offline ration distribution without biometric verification to prevent starvation in marooned areas.",
  },
  {
    id: "cold_storage_warehouses",
    name: "Commercial Cold Storage Warehouses",
    deptId: "markets_food",
    code: "MF-3",
    reserveHours: 12,
    criticality: 0.81,
    description: "Ammonia-chilled multi-commodity cold stores holding potatoes, fruits, butter, and processed frozen foods.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 240, reason: "Refrigeration compressors shut down; thermal inertia sustains internal temperatures for only 12 to 18 hours." },
    ],
    citizenAdvisory: "Consume fresh perishable produce quickly; inspect chilled poultry and dairy for spoilage odor before cooking.",
    authorityAction: "Requisition industrial generator fuel to keep high-value potato and fruit seed cold storages chilled.",
  },

  // 11. HEALTHCARE & CRITICAL MEDICINE
  {
    id: "trauma_icus",
    name: "Level-1 Trauma Centers & ICU Wards",
    deptId: "healthcare",
    code: "HC-1",
    reserveHours: 2,
    criticality: 0.99,
    description: "Intensive care units, ventilators, neonatal incubators, and emergency surgical operating theaters.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 30, reason: "Hospital backup generators run out of diesel after 6 to 12 hours of continuous duty." },
      { targetId: "medical_oxygen_supply", weight: 0.98, lagMinutes: 60, reason: "Loss of bulk liquid oxygen pressure deprives ventilators and life-support wards within minutes." },
      { targetId: "drinking_water_plants", weight: 0.85, lagMinutes: 120, reason: "Autoclave sterilization, dialysis machines, and hospital sanitation collapse without running water." },
    ],
    citizenAdvisory: "Use hospital emergency rooms ONLY for life-threatening trauma; consult tele-medicine for minor ailments to leave beds open.",
    authorityAction: "Establish a dedicated military diesel tanker link to major trauma centers and activate emergency oxygen cylinder buffer banks.",
  },
  {
    id: "medical_oxygen_supply",
    name: "Bulk Liquid Medical Oxygen (LMO) Storage",
    deptId: "healthcare",
    code: "HC-2",
    reserveHours: 8,
    criticality: 0.99,
    description: "Vacuum-insulated cryogenic tanks holding liquid oxygen at -183°C connected to hospital pipeline manifolds.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.9, lagMinutes: 240, reason: "Cryogenic road tankers cannot navigate blocked or submerged mountain highways." },
      { targetId: "industrial_gas_plants", weight: 0.85, lagMinutes: 360, reason: "Air-separation plants in industrial clusters trip when high-voltage grid fails." },
    ],
    citizenAdvisory: "Patients requiring home oxygen concentrators should register with district emergency medical officers immediately.",
    authorityAction: "Dispatch police-escorted green corridors for cryogenic oxygen tankers and air-lift portable oxygen cylinders via IAF.",
  },
  {
    id: "blood_banks_pharmacy",
    name: "Regional Blood Banks & Vaccine Depots",
    deptId: "healthcare",
    code: "HC-3",
    reserveHours: 6,
    criticality: 0.92,
    description: "Specialized cold-storage units keeping whole blood, platelets, anti-rabies vaccines, and insulin viable.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 180, reason: "Blood bank refrigerators must stay strictly between 2°C and 6°C; power failure ruins precious blood stocks." },
    ],
    citizenAdvisory: "Healthy citizens are urged to donate blood at designated Red Cross camp centers to replenish emergency bank inventories.",
    authorityAction: "Transfer blood bank stocks to solar-hybrid cold storage units and requisition dry-ice from industrial vendors.",
  },
  {
    id: "ambulance_fleet",
    name: "108 / 102 Emergency Ambulance Fleets",
    deptId: "healthcare",
    code: "HC-4",
    reserveHours: 3,
    criticality: 0.95,
    description: "Advanced and basic life support ambulances responding to emergency calls across cities and rural villages.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.9, lagMinutes: 30, reason: "Paralyzing traffic gridlock and bridge collapses increase response transit from 12 min to over 90 min." },
      { targetId: "telecom_towers", weight: 0.85, lagMinutes: 15, reason: "Inability to dial 108 or route GPS dispatches leaves ambulances wandering blindly without addresses." },
      { targetId: "fuel_refineries", weight: 0.8, lagMinutes: 120, reason: "Empty fuel pump stations prevent ambulance fleets from refueling during round-the-clock rescue runs." },
    ],
    citizenAdvisory: "Yield right of way immediately to sirens; do not drive in emergency breakdown lanes.",
    authorityAction: "Designate priority fuel pumps strictly for ambulances and deploy satellite radios to ambulance dispatchers.",
  },

  // 12. TELECOMMUNICATIONS
  {
    id: "telecom_towers",
    name: "Cellular Base Stations (4G/5G) & Towers",
    deptId: "telecom",
    code: "TC-1",
    reserveHours: 4,
    criticality: 0.97,
    description: "Macro cellular towers providing mobile broadband, voice calling, and cell-broadcast disaster warnings.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 180, reason: "Tower backup lead-acid batteries deplete after 3 to 4 hours of grid blackout, plunging areas into darkness." },
      { targetId: "fiber_backhaul", weight: 0.9, lagMinutes: 60, reason: "Landslides and excavator ditches snap underground fiber optic cables, disconnecting towers." },
    ],
    citizenAdvisory: "Switch phone to battery-saver mode; send short SMS texts instead of placing voice calls or streaming video.",
    authorityAction: "Deploy mobile COW (Cell-on-Wheels) vans with satellite backhaul and diesel generators to disaster ground-zero.",
  },
  {
    id: "fiber_backhaul",
    name: "Optical Fiber Backhaul & Earth Stations",
    deptId: "telecom",
    code: "TC-2",
    reserveHours: 8,
    criticality: 0.94,
    description: "Underground long-haul optical fiber lines linking telephone exchanges, data centers, and ISP nodes.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.7, lagMinutes: 120, reason: "Bridge washouts and road cave-ins shear optical fiber ducts laid along highway rights-of-way." },
    ],
    citizenAdvisory: "In total mobile blackout, listen to battery-operated transistor radios tuned to All India Radio (AIR) emergency broadcasts.",
    authorityAction: "Reroute internet traffic through redundant fiber rings and deploy satellite VSAT terminals to collectorates.",
  },
  {
    id: "emergency_112_routing",
    name: "National Emergency Response System (112 ERSS)",
    deptId: "telecom",
    code: "TC-3",
    reserveHours: 6,
    criticality: 0.98,
    description: "Centralized computer-aided dispatch connecting callers to Police, Fire, Ambulance, and Disaster Helplines.",
    upstreamDependencies: [
      { targetId: "telecom_towers", weight: 0.9, lagMinutes: 30, reason: "Tower blackouts prevent distress callers from connecting to 112 dispatch centers." },
      { targetId: "it_data_centers", weight: 0.85, lagMinutes: 45, reason: "Server downtime halts automatic caller location identification (CAD) displays." },
    ],
    citizenAdvisory: "If 112 cannot connect on your mobile network, try emergency SOS; devices will roam onto ANY available carrier.",
    authorityAction: "Activate decentralized VHF wireless police wireless nets to record and dispatch rescue missions locally.",
  },

  // 13. TOURISM & PILGRIMAGE CORRIDORS
  {
    id: "pilgrim_corridors",
    name: "High-Altitude Pilgrimage Shrines & Trek Corridors",
    deptId: "tourism_hospitality",
    code: "TH-1",
    reserveHours: 12,
    criticality: 0.83,
    description: "Sacred shrines in high Himalayas (e.g. Kedarnath, Badrinath, Amarnath) hosting tens of thousands of pilgrims.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.95, lagMinutes: 60, reason: "Single-lane mountain road washouts trap thousands of pilgrims on exposed high-altitude ridgelines." },
      { targetId: "telecom_towers", weight: 0.8, lagMinutes: 120, reason: "Communication loss creates widespread panic among families across the country." },
    ],
    citizenAdvisory: "Never proceed on pilgrim treks during red weather warnings; take shelter in designated base camps.",
    authorityAction: "Halt onward pilgrim registration at base towns (Rishikesh, Jammu) and air-drop emergency rations and blankets.",
  },
  {
    id: "cable_cars_ropeways",
    name: "Passenger Ropeways & Hill Cable Cars",
    deptId: "tourism_hospitality",
    code: "TH-2",
    reserveHours: 1,
    criticality: 0.8,
    description: "Aerial ropeways transporting tourists across valleys and up steep cliffs.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 10, reason: "Loss of main power halts cable car cars mid-span over deep gorges." },
    ],
    citizenAdvisory: "Stay calm inside halted cable car cabins; do not attempt to pry doors open; wait for motorized rescue cradles.",
    authorityAction: "Mandate immediate auxiliary diesel rescue engine start to slowly bring all stranded cabins into the terminal station.",
  },

  // 14. ENVIRONMENT, FORESTS & CLIMATE
  {
    id: "forest_fire_towers",
    name: "Forest Fire Watchtowers & Catchments",
    deptId: "environment_forest",
    code: "EF-1",
    reserveHours: 24,
    criticality: 0.76,
    description: "Watchtowers, drone reconnaissance stations, and firebreak corridors in dry deciduous and pine forests.",
    upstreamDependencies: [
      { targetId: "telecom_towers", weight: 0.75, lagMinutes: 90, reason: "Inability to relay GPS coordinates of fresh fire hotspots allows minor blazes to engulf mountain slopes." },
    ],
    citizenAdvisory: "Do not discard lit cigarette butts or cook food in open forest glades during summer heatwaves.",
    authorityAction: "Mobilize forest range quick-response teams with back-pack blowers and requisition IAF Bambi bucket water helicopters.",
  },
  {
    id: "mangrove_shields",
    name: "Coastal Mangrove Surge Buffers",
    deptId: "environment_forest",
    code: "EF-2",
    reserveHours: 72,
    criticality: 0.85,
    description: "Sundarbans, Bhitarkanika, and Pichavaram dense mangrove estuaries that dissipate 60% of cyclone storm surges.",
    upstreamDependencies: [
      { targetId: "weather_satellites", weight: 0.7, lagMinutes: 360, reason: "Tidal surge surge height predictions dictate downstream bund reinforcement." },
    ],
    citizenAdvisory: "Respect mangrove conservation zones; these natural barrier forests save seaside villages from tidal erasure.",
    authorityAction: "Reinforce sluice gates at the periphery of mangrove channels to prevent hyper-saline inundation of farm fields.",
  },

  // 15. BANKING, UPI & DIGITAL FINANCE
  {
    id: "banking_upi_atm",
    name: "ATM Networks & Cash Dispensation",
    deptId: "banking_finance",
    code: "BF-1",
    reserveHours: 6,
    criticality: 0.86,
    description: "Physical ATMs dispensing emergency currency to citizens when local retail card terminals fail.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 180, reason: "ATM units shut down once UPS batteries exhaust; cash cannot be withdrawn." },
      { targetId: "telecom_towers", weight: 0.9, lagMinutes: 60, reason: "Loss of VSAT or mobile network isolates ATM from core banking systems." },
    ],
    citizenAdvisory: "Keep a contingency cash stash (₹3,000 to ₹5,000 in small notes) in your home emergency kit at all times.",
    authorityAction: "Deploy mobile ATM vans equipped with satellite connectivity and escort cash-replenishment armed security vans.",
  },
  {
    id: "npci_upi_clearing",
    name: "NPCI / UPI Real-Time Digital Payment Switch",
    deptId: "banking_finance",
    code: "BF-2",
    reserveHours: 4,
    criticality: 0.94,
    description: "Unified Payments Interface (UPI) handling over 400 million daily retail payment transactions.",
    upstreamDependencies: [
      { targetId: "it_data_centers", weight: 0.95, lagMinutes: 30, reason: "Disruption at primary payment gateway data centers freezes QR code merchant payments nationwide." },
      { targetId: "telecom_towers", weight: 0.85, lagMinutes: 15, reason: "Smartphones cannot transmit OTPs or authentication packets to UPI servers." },
    ],
    citizenAdvisory: "Be prepared to trade in cash or community barter if mobile digital payments fail during severe storms.",
    authorityAction: "Enable offline UPI-Lite store-and-forward transaction limits for purchase of life-saving medicine and food.",
  },

  // 16. URBAN MUNICIPAL INFRASTRUCTURE
  {
    id: "urban_drainage",
    name: "Stormwater Pumping Stations & Sluices",
    deptId: "urban_infrastructure",
    code: "UI-1",
    reserveHours: 2,
    criticality: 0.95,
    description: "High-volume Archimedes pumps and tidal flaps preventing coastal and river city streets from turning into canals.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 20, reason: "Pumps shut down during city power outages, causing urban underpasses to fill with 10 feet of water." },
      { targetId: "fuel_refineries", weight: 0.8, lagMinutes: 120, reason: "Lack of diesel fuel prevents backup stormwater de-watering pumps from running continuously." },
    ],
    citizenAdvisory: "Never drive into flooded subways or waterlogged roads; underwater open manholes present deadly hazards.",
    authorityAction: "Position auxiliary tractor-driven de-watering pumps and clear silt trash-screens ahead of heavy monsoon deluges.",
  },
  {
    id: "fire_rescue_brigades",
    name: "Municipal Fire & Rescue Brigades",
    deptId: "urban_infrastructure",
    code: "UI-2",
    reserveHours: 3,
    criticality: 0.96,
    description: "Fire tender stations, hydraulic turntable ladders, and chemical hazmat decontamination units.",
    upstreamDependencies: [
      { targetId: "drinking_water_plants", weight: 0.9, lagMinutes: 45, reason: "City fire hydrants run dry if municipal water mains lose pressure, crippling structural firefighting." },
      { targetId: "highway_corridors", weight: 0.85, lagMinutes: 25, reason: "Severe street congestion slows 40-ton fire trucks from reaching burning collapsed buildings." },
    ],
    citizenAdvisory: "Evacuate high-rise buildings via staircases; NEVER use elevators during an earthquake or electrical fire.",
    authorityAction: "Connect fire engines to lake and swimming pool reserves; declare fire routes strictly clear of parked vehicles.",
  },

  // 17. HEAVY INDUSTRIES & CHEMICALS
  {
    id: "chemical_plants",
    name: "HAZMAT Chemical Factories & Gas Storage",
    deptId: "heavy_industries",
    code: "HI-1",
    reserveHours: 4,
    criticality: 0.93,
    description: "Facilities storing liquid chlorine, phosgene, liquefied ammonia, and flammable solvents.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.9, lagMinutes: 30, reason: "Loss of refrigeration and scrubber circulation pumps can trigger runaway pressure buildup and toxic leaks." },
      { targetId: "urban_drainage", weight: 0.75, lagMinutes: 60, reason: "Floodwaters infiltrating chemical tanks can create explosive exothermic reactions or toxic plumes." },
    ],
    citizenAdvisory: "If chemical alarm sounds, move perpendicular to the wind direction; cover nose with wet cloth or mask.",
    authorityAction: "Mandate emergency neutralisation scrubber backup generators and verify automated fail-closed nitrogen emergency valves.",
  },
  {
    id: "chlorine_chemical_stocks",
    name: "Chlorine & Water-Purification Feedstocks",
    deptId: "chemicals_petrochem",
    code: "CP-1",
    reserveHours: 24,
    criticality: 0.9,
    description: "Pressurized one-ton chlorine tonners essential for treating municipal drinking water.",
    upstreamDependencies: [
      { targetId: "chemical_plants", weight: 0.9, lagMinutes: 720, reason: "Shutdown of chlor-alkali electrolysis units halts chlorine production, threatening municipal water safety." },
      { targetId: "highway_corridors", weight: 0.8, lagMinutes: 360, reason: "Specialized chlorine transport trucks restricted from traveling on damaged road bridges." },
    ],
    citizenAdvisory: "Support local municipal water chlorination drives; do not touch discarded pressurized gas cylinders.",
    authorityAction: "Requisition safe military escorts for chlorine cylinder convoys to city water filtration plants.",
  },

  // 18. MINES & COAL
  {
    id: "coal_mines_rakes",
    name: "Open-Cast Coal Mines & Rail Rakes",
    deptId: "mines_coal",
    code: "MC-1",
    reserveHours: 48,
    criticality: 0.87,
    description: "Large pithead coal mines in Jharkhand, Odisha, and Chhattisgarh feeding national thermal power plants.",
    upstreamDependencies: [
      { targetId: "urban_drainage", weight: 0.8, lagMinutes: 480, reason: "Flooding of open-pit mining benches submerges heavy excavators, halting coal extraction." },
      { targetId: "rail_freight_corridors", weight: 0.9, lagMinutes: 720, reason: "Shortage of empty rail wagons halts pithead coal evacuation, clogging conveyor systems." },
    ],
    citizenAdvisory: "Communities near coal-waste dumps should watch for slope mudslides during torrential monsoon rains.",
    authorityAction: "Deploy high-capacity submersible de-watering pumps to keep active coal pit bottom benches dry.",
  },

  // 19. EDUCATION (SHELTERS)
  {
    id: "govt_school_shelters",
    name: "Government Schools (Primary Evacuation Centers)",
    deptId: "education",
    code: "ED-1",
    reserveHours: 12,
    criticality: 0.93,
    description: "Multi-story concrete school buildings pre-designated as community cyclone and flood evacuation shelters.",
    upstreamDependencies: [
      { targetId: "drinking_water_plants", weight: 0.85, lagMinutes: 180, reason: "Shelters turn into disease hotspots if water supply cuts out, leaving 1,000 evacuees without sanitation." },
      { targetId: "power_substations", weight: 0.75, lagMinutes: 240, reason: "Lack of lighting and ceiling fans in crowded halls causes heat exhaustion among children and elderly." },
      { targetId: "pds_ration_shops", weight: 0.8, lagMinutes: 360, reason: "Community kitchens run out of grains and cooking gas within 24 hours without resupply." },
    ],
    citizenAdvisory: "Proceed immediately to designated school shelters when local village talathi/patwari issues evacuation alert.",
    authorityAction: "Deliver modular mobile sanitation bio-toilets and install solar-powered battery lamps in all school shelter halls.",
  },

  // 20. HOME AFFAIRS & POLICE
  {
    id: "ndrf_sdrf_battalions",
    name: "NDRF / SDRF Specialized Search & Rescue",
    deptId: "home_affairs",
    code: "HA-1",
    reserveHours: 6,
    criticality: 0.98,
    description: "Trained flood rescue teams equipped with inflatable motorboats, acoustic life-detectors, and canine squads.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.85, lagMinutes: 60, reason: "Highway washouts delay deployment of heavy rescue trucks carrying disaster equipment." },
      { targetId: "telecom_towers", weight: 0.8, lagMinutes: 30, reason: "Communication breakdown between district collectorate and field rescue boat commanders." },
      { targetId: "fuel_refineries", weight: 0.75, lagMinutes: 120, reason: "Boat outboard motors (OBMs) require clean petrol and 2T oil to operate search sorties." },
    ],
    citizenAdvisory: "Signal rescue boats using brightly colored cloth or flashing mobile torch lights from your rooftop.",
    authorityAction: "Air-lift inflatable boats and satellite-linked comms packs directly into isolated villages via IAF transport helicopters.",
  },

  // 21. DEFENSE & BORDER ROADS
  {
    id: "bro_strategic_bridges",
    name: "Border Roads (BRO) Bailey Bridging Units",
    deptId: "defense_border",
    code: "DB-1",
    reserveHours: 12,
    criticality: 0.91,
    description: "Modular steel Bailey bridge assembly units capable of bridging 60-meter chasms within 36 hours.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.7, lagMinutes: 180, reason: "Heavy trailers transporting steel trusses cannot navigate narrow landslide-covered mountain roads." },
    ],
    citizenAdvisory: "Observe weight limit and single-vehicle-at-a-time rules when crossing newly erected temporary Bailey bridges.",
    authorityAction: "Requisition BRO heavy recovery taskforces immediately upon confirmation of arterial bridge collapse.",
  },

  // 22. COASTAL FISHERIES
  {
    id: "fishing_harbor_fleets",
    name: "Mechanized Trawler Fleets & Marine Harbors",
    deptId: "coastal_fisheries",
    code: "CF-1",
    reserveHours: 18,
    criticality: 0.82,
    description: "Over 50,000 motorized fishing boats, ice-flaking plants, and coastal fish auction halls.",
    upstreamDependencies: [
      { targetId: "weather_satellites", weight: 0.95, lagMinutes: 120, reason: "Failure to receive NavIC/cyclone broadcast leaves deep-sea fishermen unaware of incoming gale winds." },
      { targetId: "power_substations", weight: 0.75, lagMinutes: 360, reason: "Ice plants shut down; daily catch rots within 6 hours, wiping out coastal fishermen savings." },
    ],
    citizenAdvisory: "Fishermen must heed 'Red Signal' port warnings and refrain from venturing out to sea under any circumstances.",
    authorityAction: "Broadcast urgent NavIC satellite audio warnings to all active marine fishing vessels to steer toward the nearest safe harbor.",
  },

  // 23. INFORMATION TECHNOLOGY & DATA CENTERS
  {
    id: "it_data_centers",
    name: "State & National Cloud Data Centers",
    deptId: "it_electronics",
    code: "IT-1",
    reserveHours: 8,
    criticality: 0.97,
    description: "Tier-3/4 server facilities hosting government portals, citizen registries, disaster portals, and banking switches.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.95, lagMinutes: 60, reason: "Massive chiller and server room cooling units trip; thermal emergency shut-off activates within minutes." },
      { targetId: "fiber_backhaul", weight: 0.9, lagMinutes: 30, reason: "Severed dark-fiber rings isolate government databases from nationwide users." },
    ],
    citizenAdvisory: "Expect intermittent latency on government e-services and official disaster portals during high-volume server spikes.",
    authorityAction: "Fail-over disaster management database operations to mirrored secondary disaster-recovery (DR) data centers in other states.",
  },

  // 24. COMMERCE & FREIGHT SUPPLY CHAINS
  {
    id: "truck_freight_terminals",
    name: "Inter-State Truck Logistics Hubs & Warehouses",
    deptId: "commerce_logistics",
    code: "CL-1",
    reserveHours: 24,
    criticality: 0.86,
    description: "Multimodal logistics parks holding FMCG goods, packaged water, clothes, and emergency provisions.",
    upstreamDependencies: [
      { targetId: "highway_corridors", weight: 0.95, lagMinutes: 180, reason: "Highway gridlock leaves 10,000 trucks parked on road shoulders, choking regional goods distribution." },
      { targetId: "fuel_refineries", weight: 0.85, lagMinutes: 360, reason: "Diesel rationing slows long-haul truck dispatch to a complete crawl." },
    ],
    citizenAdvisory: "Expect temporary delivery delays for online e-commerce parcels and retail consumer goods.",
    authorityAction: "Requisition commercial freight truck fleets under disaster management powers to transport priority relief tents and water bottles.",
  },

  // 25. RURAL DEVELOPMENT & PANCHAYATS
  {
    id: "rural_roads",
    name: "PMGSY All-Weather Rural Road Links",
    deptId: "rural_development",
    code: "RD-1",
    reserveHours: 4,
    criticality: 0.88,
    description: "Single-lane asphalt rural roads connecting isolated farming hamlets to national highway lifelines.",
    upstreamDependencies: [
      { targetId: "river_embankments", weight: 0.85, lagMinutes: 90, reason: "Flood embankment breaches submerge rural culverts, cutting off interior villages." },
    ],
    citizenAdvisory: "Village residents should avoid walking along washed-out culverts where rushing water has eroded pavement edges.",
    authorityAction: "Deploy tractor-mounted backhoes to clear mudslides and lay temporary crushed-gravel bypass causeways.",
  },

  // 26. TEXTILES & EMERGENCY FABRICS
  {
    id: "emergency_textiles",
    name: "Waterproof Tarpaulins & Blanket Mills",
    deptId: "textiles",
    code: "TX-1",
    reserveHours: 48,
    criticality: 0.75,
    description: "Manufacturing hubs producing HDPE waterproof tarpaulins, family relief tents, and wool blankets.",
    upstreamDependencies: [
      { targetId: "chemical_plants", weight: 0.8, lagMinutes: 720, reason: "Shortage of high-density polyethylene polymer granules halts tarpaulin fabrication." },
      { targetId: "power_substations", weight: 0.7, lagMinutes: 360, reason: "Textile weaving and laminating machinery shuts down during industrial power rationing." },
    ],
    citizenAdvisory: "Conserve existing plastic sheeting and waterproof coverings for thatch roofs before seasonal rains arrive.",
    authorityAction: "Purchase buffer stocks of 500,000 waterproof family tarpaulins directly from textile federations for immediate air-dropping.",
  },

  // 27. LABOUR & MIGRANT WELFARE
  {
    id: "migrant_worker_hubs",
    name: "Migrant Labour Transit Shelters & Welfare",
    deptId: "labour_employment",
    code: "LE-1",
    reserveHours: 18,
    criticality: 0.84,
    description: "Transit housing colonies and registration hubs supporting inter-state construction and agricultural workers.",
    upstreamDependencies: [
      { targetId: "pds_ration_shops", weight: 0.85, lagMinutes: 240, reason: "Migrants lack local ration cards; food security dries up when daily construction wages halt." },
      { targetId: "drinking_water_plants", weight: 0.8, lagMinutes: 180, reason: "Densely packed labor settlements face acute disease outbreaks when clean water tankers stop." },
    ],
    citizenAdvisory: "Informal and migrant workers should register with the nearest municipal relief desk for free meals and transit assistance.",
    authorityAction: "Activate the 'One Nation One Ration Card' emergency protocol to provide free cooked meals and medical screening.",
  },

  // 28. SPACE TELEMETRY & ISRO
  {
    id: "weather_satellites",
    name: "INSAT Meteorological & NavIC Satellite Constellation",
    deptId: "space_science",
    code: "SS-1",
    reserveHours: 1,
    criticality: 0.99,
    description: "Geostationary meteorological imagers and NavIC positioning satellites monitoring cyclones and cloudbursts.",
    upstreamDependencies: [
      { targetId: "it_data_centers", weight: 0.9, lagMinutes: 20, reason: "Earth tracking station servers must relay live multi-spectral satellite imagery to IMD forecasters." },
    ],
    citizenAdvisory: "Follow only verified satellite-derived weather warnings from IMD and RAKSHAK; ignore unverified social media rumors.",
    authorityAction: "Switch master satellite ground control stations to dedicated uninterruptible flywheel generator banks.",
  },

  // 29. WOMEN & CHILD NUTRITION
  {
    id: "anganwadi_centers",
    name: "Anganwadi Centers & Infant Nutrition Depots",
    deptId: "women_child",
    code: "WC-1",
    reserveHours: 24,
    criticality: 0.92,
    description: "Over 1.3 million village grassroots centers providing ready-to-use therapeutic food (RUTF) and infant health care.",
    upstreamDependencies: [
      { targetId: "dairy_milk_collection", weight: 0.85, lagMinutes: 360, reason: "Disruption of milk and micronutrient paste supply jeopardizes malnourished infants and pregnant mothers." },
      { targetId: "rural_roads", weight: 0.75, lagMinutes: 240, reason: "Anganwadi outreach workers unable to reach waterlogged village hamlets." },
    ],
    citizenAdvisory: "Mothers should breastfeed infants; seek Anganwadi worker assistance immediately if a child displays diarrhea or fever.",
    authorityAction: "Pre-position sealed infant baby-food cartons and oral rehydration salt (ORS) packets in every designated village shelter.",
  },

  // 30. INDUSTRIAL GASES & HAZMAT (Cross-link)
  {
    id: "industrial_gas_plants",
    name: "Industrial Cryogenic Gas Plants (Oxygen & Nitrogen)",
    deptId: "heavy_industries",
    code: "HI-2",
    reserveHours: 6,
    criticality: 0.96,
    description: "Air-separation plants producing high-purity liquid medical oxygen (LMO) and nitrogen for cooling.",
    upstreamDependencies: [
      { targetId: "power_substations", weight: 0.98, lagMinutes: 15, reason: "Cryogenic air-liquefaction requires continuous gigawatt electric power; interruption halts oxygen separation immediately." },
    ],
    citizenAdvisory: "Industrial factories should yield cryogenic liquid tankers to medical hospitals during emergency declarations.",
    authorityAction: "Place all cryogenic oxygen manufacturing units on dedicated protected electrical grid feeders with zero load-shedding.",
  },
];
