// Infrastructure Resilience & Cascading Multi-Hazard Modeling Data
// Models critical lifelines: Power Grid, Transportation/Bridges, Water Utilities, Acute Healthcare, Telecom & Shelters.

export const DOMINO_SCENARIOS = [
  {
    id: "bridge_b7",
    name: "Bridge B7 Structural Collapse",
    badge: "Transportation Lifeline Shock",
    category: "Bridge & Mobility",
    icon: "fa-bridge-water",
    trigger: {
      name: "Bridge B7 (Central River Span)",
      code: "B7",
      type: "Transportation / Bridge",
      event: "Pier Scour & Structural Collapse",
      detail: "Heavy hydraulic pressure & river swell shears central pier 3; arterial bridge closes instantly.",
      nominalCapacity: "45,000 veh/day",
      nominalStatus: "🟢 Nominal (45,000 veh/day flowing)",
    },
    beforeSteps: [
      { id: "b7", code: "B7", name: "Bridge B7", role: "Arterial River Span", status: "nominal", icon: "fa-bridge", metric: "Flow: 45,000 veh/d (Nominal)" },
      { id: "r12", code: "R12", name: "Road R12", role: "North Ring Bypass", status: "nominal", icon: "fa-road", metric: "Flow: 22k / Cap: 35k (63% load)" },
      { id: "r15", code: "R15", name: "Road R15", role: "District Feeder Corridor", status: "nominal", icon: "fa-route", metric: "Flow: 18k / Cap: 30k (60% load)" },
      { id: "h2", code: "H2", name: "Hospital H2", role: "Regional Trauma Center", status: "nominal", icon: "fa-hospital", metric: "Ambulance transit: 8 mins" },
      { id: "s4", code: "S4", name: "Shelter S4", role: "Community Evacuation Center", status: "nominal", icon: "fa-tents", metric: "Relief logistics link active" },
    ],
    afterSteps: [
      {
        id: "b7",
        code: "B7",
        name: "Bridge B7",
        role: "Primary Failure",
        severity: "critical", // 🔴
        severityColor: "red",
        indicator: "🔴",
        cause: "Physical Bridge Collapse",
        impact: "Arterial severed — 45,000 veh/day diverted to secondary ring roads instantly.",
        time: "T+0 min",
      },
      {
        id: "r12",
        code: "R12",
        name: "Road R12",
        role: "First-Order Overload",
        severity: "warning", // 🟠
        severityColor: "orange",
        indicator: "🟠",
        cause: "Traffic Diversion Rerouting",
        impact: "Traffic flow surges from 22k to 56,000 veh/day (160% capacity). Gridlock speeds drop to 4 km/h.",
        time: "T+12 min",
      },
      {
        id: "r15",
        code: "R15",
        name: "Road R15",
        role: "Secondary Corridor Failure",
        severity: "critical", // 🔴
        severityColor: "red",
        indicator: "🔴",
        cause: "Cascading Pavement & Signal Lock",
        impact: "Spillover gridlock blocks vital intersection. Emergency vehicles and supply convoys completely trapped.",
        time: "T+28 min",
      },
      {
        id: "h2",
        code: "H2",
        name: "Hospital H2 Accessibility",
        role: "Critical Healthcare Impact",
        severity: "warning", // 🟠
        severityColor: "orange",
        indicator: "🟠",
        cause: "Trauma Corridor Blockage",
        impact: "Ambulance response transit delayed from 8 mins to 58 mins. 650 acute trauma beds isolated.",
        time: "T+45 min",
      },
      {
        id: "s4",
        code: "S4",
        name: "Shelter S4 Logistics",
        role: "Relief Supply Disruption",
        severity: "critical", // 🔴
        severityColor: "red",
        indicator: "🔴",
        cause: "Access Arterial Paralyzed",
        impact: "Emergency water tankers and food delivery trucks unable to navigate access road. 4,200 evacuees stranded.",
        time: "T+60 min",
      },
    ],
    summaryStatement: "1 bridge failure → 4 downstream disruptions",
    summaryStats: {
      downstreamCount: 4,
      populationAffected: "185,000 citizens",
      transitDelay: "+50 min ambulance latency",
      healthcareLoss: "650 trauma beds isolated",
      resilienceDrop: "100% → 28%",
    },
    intervention: {
      title: "Reinforce Road R12 with Modular Quick-Deploy Bypass Span",
      targetAsset: "Road R12",
      cost: "₹14.8 Crore",
      costUSD: "$1.75M",
      impactReduction: "68%",
      reductionValue: 68,
      leadTime: "24-48 Hours Deployable (Pre-Staged Modular Steel Bailey)",
      mechanism:
        "Installs rapid modular dual-lane bypass ramps on Road R12 + adaptive emergency AI signal preemption. Increases R12 capacity from 35,000 to 62,000 veh/day, safely absorbing the diverted bridge traffic.",
      dominoOutcome: "Cascade Intercepted at R12! Stops secondary failure of Road R15, Hospital H2, and Shelter S4.",
      afterInterventionSteps: [
        { id: "b7", code: "B7", name: "Bridge B7", status: "failed", indicator: "🔴", note: "Bridge failed (Unavoidable structural shock)" },
        { id: "r12", code: "R12", name: "Road R12 [REINFORCED]", status: "protected", indicator: "🛡️", note: "Bypass active — Absorbs 54k veh/d within expanded 62k capacity (Fluid)" },
        { id: "r15", code: "R15", name: "Road R15", status: "nominal", indicator: "🟢", note: "Protected — Normal traffic flow maintained" },
        { id: "h2", code: "H2", name: "Hospital H2", status: "nominal", indicator: "🟢", note: "Protected — Ambulance transit nominal (9 mins)" },
        { id: "s4", code: "S4", name: "Shelter S4", status: "nominal", indicator: "🟢", note: "Protected — Relief logistics unimpeded" },
      ],
      roi: "₹82 Crore in cascading medical, transport, and economic paralysis avoided (5.5x ROI)",
    },
  },
  {
    id: "substation_alpha",
    name: "Substation Alpha Inundation",
    badge: "Energy Grid Domino",
    category: "Power & Utilities",
    icon: "fa-bolt",
    trigger: {
      name: "Substation Alpha (220kV Grid Feed)",
      code: "S-ALPHA",
      type: "Power / Transmission Hub",
      event: "Transformer Yard Flash Flood",
      detail: "River embankment crests floodwall; high-voltage switchgear short-circuits, cutting 140MW power feed.",
      nominalCapacity: "140 MW power delivery",
      nominalStatus: "🟢 Nominal (140 MW flowing to 280,000 residents)",
    },
    beforeSteps: [
      { id: "s-alpha", code: "S-ALPHA", name: "Substation Alpha", role: "Primary Grid Infeed", status: "nominal", icon: "fa-bolt", metric: "140 MW / 100% capacity" },
      { id: "w1", code: "W1", name: "Water Pumping W1", role: "River Intake Station", status: "nominal", icon: "fa-faucet", metric: "Pumping 4,200 m³/h" },
      { id: "t3", code: "T3", name: "Telecom Tower T3", role: "Emergency Macro Cell", status: "nominal", icon: "fa-tower-cell", metric: "Battery reserve: 100%" },
      { id: "c112", code: "C112", name: "112 Dispatch Hub", role: "Emergency Operations", status: "nominal", icon: "fa-headset", metric: "Dispatch latency: <15s" },
      { id: "h1", code: "H1", name: "District Hospital H1", role: "Acute Surgical Hospital", status: "nominal", icon: "fa-hospital", metric: "Mains power active" },
    ],
    afterSteps: [
      {
        id: "s-alpha",
        code: "S-ALPHA",
        name: "Substation Alpha",
        role: "Primary Failure",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "Transformer Submersion & Breaker Trip",
        impact: "Total power trip across Sector 4. 280,000 citizens plunged into blackout.",
        time: "T+0 min",
      },
      {
        id: "w1",
        code: "W1",
        name: "Water Pumping W1",
        role: "Hydraulic Inflow Cut",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "High-Voltage Pump Motor Depower",
        impact: "Intake pumps shut down. Municipal water pressure drops to zero for 140,000 households.",
        time: "T+8 min",
      },
      {
        id: "t3",
        code: "T3",
        name: "Telecom Tower T3",
        role: "Communications Degrade",
        severity: "warning",
        severityColor: "orange",
        indicator: "🟠",
        cause: "Backup Battery Depletion",
        impact: "Grid loss forces battery backup; after 30 mins, transmission power throttles 70%, dropping emergency calls.",
        time: "T+35 min",
      },
      {
        id: "c112",
        code: "C112",
        name: "112 Dispatch Hub",
        role: "Command Blindness",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "Cellular Telemetry Packet Drop",
        impact: "Ambulance GPS tracking and citizen SOS calls fail to route. Dispatchers forced to voice-only radio.",
        time: "T+50 min",
      },
      {
        id: "h1",
        code: "H1",
        name: "District Hospital H1",
        role: "Emergency Generator Stress",
        severity: "warning",
        severityColor: "orange",
        indicator: "🟠",
        cause: "Auxiliary Diesel Run-Hour Limit",
        impact: "Switched to backup generators. Diesel supply limited to 6 hours; air conditioning & non-ICU wards shed load.",
        time: "T+65 min",
      },
    ],
    summaryStatement: "1 substation failure → 4 downstream disruptions",
    summaryStats: {
      downstreamCount: 4,
      populationAffected: "280,000 without power & water",
      transitDelay: "112 SOS call failure rate: 42%",
      healthcareLoss: "Hospital on finite 6h diesel clock",
      resilienceDrop: "100% → 19%",
    },
    intervention: {
      title: "Substation Alpha Automated Flood Barriers + 20MW Microgrid Islanding",
      targetAsset: "Substation Alpha & Water Pumping W1",
      cost: "₹18.5 Crore",
      costUSD: "$2.2M",
      impactReduction: "79%",
      reductionValue: 79,
      leadTime: "Permanent Capital Hardening",
      mechanism:
        "Installs automated pneumatic flood barrier walls around switchgear + a dedicated 20MW BESS battery microgrid with solar tie-in at Water Pumping W1.",
      dominoOutcome: "Cascade Intercepted at Substation Alpha! Power reroutes automatically, keeping pumps and telecom fully operational.",
      afterInterventionSteps: [
        { id: "s-alpha", code: "S-ALPHA", name: "Substation Alpha [PROTECTED]", status: "protected", indicator: "🛡️", note: "Pneumatic floodgates hold river swell — Grid feeds uninterrupted" },
        { id: "w1", code: "W1", name: "Water Pumping W1", status: "nominal", indicator: "🟢", note: "Protected — Dual-feed power active, normal pumping" },
        { id: "t3", code: "T3", name: "Telecom Tower T3", status: "nominal", indicator: "🟢", note: "Protected — Grid power alive, cell network 100%" },
        { id: "c112", code: "C112", name: "112 Dispatch Hub", status: "nominal", indicator: "🟢", note: "Protected — Zero SOS packet drop" },
        { id: "h1", code: "H1", name: "District Hospital H1", status: "nominal", indicator: "🟢", note: "Protected — Continuous mains power, diesel saved" },
      ],
      roi: "₹140 Crore in avoided industrial blackout loss and healthcare evacuation costs",
    },
  },
  {
    id: "reservoir_dam",
    name: "Reservoir Dam Overtopping & Flash Flood",
    badge: "Compound Multi-Hazard",
    category: "Hydro & Lifeline",
    icon: "fa-water",
    trigger: {
      name: "Upper River Catchment Dam",
      code: "DAM-D1",
      type: "Hydraulic Barrier",
      event: "Cloudburst Cresting & Sluice Gate Jam",
      detail: "350mm cloudburst in catchment fills reservoir to 108% FRL; mechanical sluice failure triggers uncontrolled spillway surge.",
      nominalCapacity: "1,200 m³/s safe discharge",
      nominalStatus: "🟢 Nominal (Water level at 65% capacity)",
    },
    beforeSteps: [
      { id: "dam-d1", code: "DAM-D1", name: "Upper Dam D1", role: "Flood Control Reservoir", status: "nominal", icon: "fa-water", metric: "Storage: 65% FRL (Nominal)" },
      { id: "hway-h4", code: "HWAY-H4", name: "Highway H4", role: "Primary Evacuation Corridor", status: "nominal", icon: "fa-road", metric: "Traffic: 38,000 veh/d (Fluid)" },
      { id: "fuel-f2", code: "FUEL-F2", name: "Fuel Storage Depot", role: "Regional Diesel Logistics", status: "nominal", icon: "fa-gas-pump", metric: "Inventory: 4.5M Liters" },
      { id: "gen-med", code: "GEN-MED", name: "Hospital Generator Supply", role: "Critical Lifeline Fuel", status: "nominal", icon: "fa-truck-medical", metric: "Daily delivery active" },
      { id: "icu-main", code: "ICU-MAIN", name: "Apex Trauma ICU", role: "Intensive Care Units", status: "nominal", icon: "fa-heart-pulse", metric: "120 ventilators online" },
    ],
    afterSteps: [
      {
        id: "dam-d1",
        code: "DAM-D1",
        name: "Upper Dam D1",
        role: "Primary Failure",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "Uncontrolled Spillway Surge",
        impact: "4,800 m³/s torrent floods downstream valley and highway approaches.",
        time: "T+0 min",
      },
      {
        id: "hway-h4",
        code: "HWAY-H4",
        name: "Highway H4",
        role: "Corridor Submersion",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "1.8m Waterlogging & Erosion",
        impact: "Main highway blocked. 12 km evacuation jam strands 15,000 vehicles.",
        time: "T+18 min",
      },
      {
        id: "fuel-f2",
        code: "FUEL-F2",
        name: "Fuel Storage Depot",
        role: "Supply Chain Paralysis",
        severity: "warning",
        severityColor: "orange",
        indicator: "🟠",
        cause: "Depot Access Cut by Floodwaters",
        impact: "Fuel tanker trucks unable to exit terminal. Regional emergency diesel dispatch frozen.",
        time: "T+40 min",
      },
      {
        id: "gen-med",
        code: "GEN-MED",
        name: "Hospital Generator Supply",
        role: "Fuel Starvation",
        severity: "critical",
        severityColor: "red",
        indicator: "🔴",
        cause: "Depleted On-Site Tanks",
        impact: "Refueling tankers fail to arrive. Hospital diesel reserve dwindles past emergency threshold.",
        time: "T+75 min",
      },
      {
        id: "icu-main",
        code: "ICU-MAIN",
        name: "Apex Trauma ICU",
        role: "Catastrophic Patient Risk",
        severity: "warning",
        severityColor: "orange",
        indicator: "🟠",
        cause: "Power Shedding to Life-Support",
        impact: "Hospital forced to switch ventilators to internal 2h battery backups. Emergency airlift requested.",
        time: "T+90 min",
      },
    ],
    summaryStatement: "1 dam breach → 4 downstream disruptions",
    summaryStats: {
      downstreamCount: 4,
      populationAffected: "65,000 in inundation zone",
      transitDelay: "Evacuation route blocked for 15,000 vehicles",
      healthcareLoss: "120 ICU ventilators on 2h emergency clock",
      resilienceDrop: "100% → 22%",
    },
    intervention: {
      title: "Automated Catchment Early Release + Elevated Fuel Bunker Corridors",
      targetAsset: "Upper Dam & Highway H4",
      cost: "₹22.4 Crore",
      costUSD: "$2.7M",
      impactReduction: "74%",
      reductionValue: 74,
      leadTime: "Civil Works & IoT Sensor Upgrade",
      mechanism:
        "Proactive reservoir drawdown based on radar rain telemetry + construction of elevated all-weather emergency bypass ramp connecting Fuel Depot to Hospital.",
      dominoOutcome: "Cascade Intercepted at Highway H4! Peak surge routed through flood canals; fuel access corridor remains dry.",
      afterInterventionSteps: [
        { id: "dam-d1", code: "DAM-D1", name: "Upper Dam D1 [CONTROLLED]", status: "protected", indicator: "🛡️", note: "Controlled early release kept surge below crest line" },
        { id: "hway-h4", code: "HWAY-H4", name: "Highway H4 [ELEVATED]", status: "nominal", indicator: "🟢", note: "Protected — Ramp stays above flood plain, traffic fluid" },
        { id: "fuel-f2", code: "FUEL-F2", name: "Fuel Storage Depot", status: "nominal", indicator: "🟢", note: "Protected — Tankers dispatching on schedule" },
        { id: "gen-med", code: "GEN-MED", name: "Hospital Generator Supply", status: "nominal", indicator: "🟢", note: "Protected — Emergency refueling delivered" },
        { id: "icu-main", code: "ICU-MAIN", name: "Apex Trauma ICU", status: "nominal", indicator: "🟢", note: "Protected — 100% power reliability guaranteed" },
      ],
      roi: "₹185 Crore in life-support continuity and flood disaster mitigation",
    },
  },
];

// Full Interconnected Network Nodes (for network topology view)
export const NETWORK_NODES = [
  { id: "B7", label: "Bridge B7", category: "transport", x: 420, y: 220, lat: 18.965, lng: 72.825, capacity: 45000, betweenness: 0.88, fragility: 4.2, status: "nominal" },
  { id: "R12", label: "Road R12 (North Ring)", category: "transport", x: 300, y: 160, lat: 18.995, lng: 72.815, capacity: 35000, betweenness: 0.74, fragility: 3.6, status: "nominal" },
  { id: "R15", label: "Road R15 (Relief Feeder)", category: "transport", x: 220, y: 280, lat: 18.945, lng: 72.835, capacity: 30000, betweenness: 0.62, fragility: 2.9, status: "nominal" },
  { id: "H2", label: "Hospital H2 (Trauma)", category: "healthcare", x: 140, y: 340, lat: 18.925, lng: 72.845, capacity: 650, betweenness: 0.91, fragility: 5.1, status: "nominal" },
  { id: "S4", label: "Shelter S4 (Relief Hub)", category: "shelter", x: 120, y: 460, lat: 18.905, lng: 72.825, capacity: 4200, betweenness: 0.45, fragility: 2.1, status: "nominal" },
  { id: "S-ALPHA", label: "Substation Alpha (220kV)", category: "power", x: 550, y: 140, lat: 19.015, lng: 72.865, capacity: 140, betweenness: 0.95, fragility: 5.8, status: "nominal" },
  { id: "W1", label: "Water Pumping W1", category: "water", x: 580, y: 290, lat: 18.975, lng: 72.885, capacity: 4200, betweenness: 0.79, fragility: 3.8, status: "nominal" },
  { id: "T3", label: "Telecom Tower T3", category: "telecom", x: 360, y: 380, lat: 18.935, lng: 72.855, capacity: 50000, betweenness: 0.68, fragility: 3.1, status: "nominal" },
  { id: "C112", label: "Central 112 Dispatch", category: "telecom", x: 280, y: 440, lat: 18.915, lng: 72.865, capacity: 25000, betweenness: 0.85, fragility: 4.5, status: "nominal" },
];

export const NETWORK_EDGES = [
  { from: "B7", to: "R12", type: "traffic", label: "Primary Diversion" },
  { from: "R12", to: "R15", type: "traffic", label: "Spillover Corridor" },
  { from: "R15", to: "H2", type: "access", label: "Ambulance Lifeline" },
  { from: "R15", to: "S4", type: "access", label: "Relief Supply Road" },
  { from: "S-ALPHA", to: "W1", type: "power", label: "11kV Pump Feed" },
  { from: "S-ALPHA", to: "T3", type: "power", label: "Cellular Grid Power" },
  { from: "S-ALPHA", to: "C112", type: "power", label: "Dispatch Hub Power" },
  { from: "T3", to: "C112", type: "comm", label: "Emergency Telemetry" },
  { from: "W1", to: "H2", type: "water", label: "Medical Water Mains" },
  { from: "C112", to: "H2", type: "comm", label: "Trauma Pre-Alert" },
];

// Disproportionately Important Bottleneck Ranking (Betweenness Centrality & Fragility)
export const BOTTLENECK_RANKINGS = [
  { rank: 1, asset: "Substation Alpha", code: "S-ALPHA", sector: "Power Grid", betweenness: 0.95, fragility: "5.8x", spof: true, downstreamLoss: "78% systemic outage", recommendation: "20MW Battery Microgrid & Flood Barrier" },
  { rank: 2, asset: "Hospital H2 (Trauma)", code: "H2", sector: "Healthcare", betweenness: 0.91, fragility: "5.1x", spof: false, downstreamLoss: "650 trauma beds isolated", recommendation: "Tri-generation generator + Dual Road Access" },
  { rank: 3, asset: "Bridge B7", code: "B7", sector: "Transportation", betweenness: 0.88, fragility: "4.2x", spof: true, downstreamLoss: "4 downstream failures (+50m transit delay)", recommendation: "Pre-staged Bailey Bridge & R12 Reinforcement" },
  { rank: 4, asset: "Central 112 Dispatch", code: "C112", sector: "Emergency Telecom", betweenness: 0.85, fragility: "4.5x", spof: false, downstreamLoss: "City-wide response blindness", recommendation: "Satellite Uplink & Dual Optical Fiber" },
  { rank: 5, asset: "Water Pumping W1", code: "W1", sector: "Water & Sanitation", betweenness: 0.79, fragility: "3.8x", spof: false, downstreamLoss: "140,000 households without potable water", recommendation: "Emergency Solar Lift Pumps & Water Buffer Tanks" },
];
